### ISSUE TITLE
Preparations for Production Running with the ROACH2

### ISSUE THREAD

**Issue by nsoblath** [project8/phasmid#2]
## Task List

This list should be roughly in the order that the tasks should be completed.  

Please check off tasks as they're completed, add new tasks to the list, and reorder as appropriate.

The responsible person should be listed after the task.
- [x] Put the ROACH 1 GbE connection on the p8 network
  - [x] Recabling (@wcpettus)
  - [x] ROACH booting off of p8portal (@wcpettus)
  - [x] Reconfigure r2daq to separate the control and data interfaces (see #1) (@anyoung)
- [x] Roach2AcquisitionInterface coding
  - [x] Move to its own source file (@cclaessens)
  - [x] Decide on and implement relationship between r2daq and Roach2AcquisitionInterface (@anyoung)
  - [x] Control of frequency windows (@cclaessens)
- [x] Psyllid Testing 1
  - [x] Demonstrate recording of egg file (@cclaessens)
  - [x] Test sequential packet recording (demonstrate or start fixing in parallel) (@cclaessens)
- [x] **DAQ Test**: Start a run with the DAQ interface and produce an egg file (@cclaessens)
- [x] Reconfigure Zeppelin's hardware
  - [x] 10 GbE connection from Zeppelin to Angelo (network card from Irene?) (@wcpettus)
  - [x] SSD moved from Irene for `/data/hot` (@wcpettus)
  - [x] 2x SSD moved from Irene for `/data/warm`, configured as RAID1 (@wcpettus)
  - [x] Network mount `/data/warm` on Angelo at `/data_zeppelin` (@nsoblath)
- [x] Data flow software on Zeppelin (@nsoblath)
  - [x] Setup golang programming environment (@nsoblath)
  - [x] Hornet (@nsoblath)
  - [x] mdreceiver (@nsoblath)
  - [x] dungbeetle (@nsoblath)
- [x] DIRAC setup on Angelo
  - [x] Create a new agent for Zeppelin (@nsoblath)
- [x] Psyllid Testing 2
  - [x] Demonstrate sequential packet recording (@cclaessens)
  - [x] Demonstrate tone reconstruction (@cclaessens)
  - [x] Demonstrate electron-signal reconstruction (@cclaessens, @nsoblath)
- [x] Other Details
  - [x] Fix Katydid reversed-frequency-axis problem
  - [x] Inform Psyllid of ROACH channels' central frequencies and frequency spans
  - [x] New config file paradigm for psyllid
- [x] **DAQ/Dataflow Test**: Start a run with the DAQ interface and end up with a file at PNNL (@cclaessens)
